- hosts: all
  become: yes
  tasks:

    - name: update OS
      apt:
        upgrade: dist

    - name: Install net-tools
      apt: 
        name: net-tools
        state: latest

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install Git
      apt:
        name: git
        state: latest

    - name: Install Python
      apt:
        name: python3
        state: latest